#                ██████████                        
#            ████          ████              _ (`-.  ('-. .-.   ('-.         .-') _  .-') _                _   .-')             
#          ██                  ██           ( (OO  )( OO )  /  ( OO ).-.    ( OO ) )(  OO) )              ( '.( OO )_           
#        ██                      ██        _.`     \,--. ,--.  / . --. /,--./ ,--,' /     '._  .-'),-----. ,--.   ,--.)         
#      ██                          ██     (__...--''|  | |  |  | \-.  \ |   \ |  |\ |'--...__)( OO'  .-.  '|   `.'   |          
#    ██                              ██    |  /  | ||   .|  |.-'-'  |  ||    \|  | )'--.  .--'/   |  | |  ||         |          
#    ██                              ██    |  |_.' ||       | \| |_.'  ||  .     |/    |  |   \_) |  |\|  ||  |'.'|  |          
#  ██        ████        ████          ██  |  .___.'|  .-.  |  |  .-.  ||  |\    |     |  |     \ |  | |  ||  |   |  |          
#  ██        ██            ██          ██  |  |     |  | |  |  |  | |  ||  | \   |     |  |      `'  '-'  '|  |   |  |          
#  ██        ████        ████          ██  `--'     `--' `--'  `--' `--'`--'  `--'     `--'        `-----' `--'   `--'          
#  ██    ░░░░                ░░░░      ██          
#  ██            ████████              ██          
#  ██  ██████              ██████      ██          
#  ██        ██          ██            ██          
#  ██        ██          ██            ██          
#  ██  ██████              ██████        ██    ██  
#  ██                                      ████  ██
#    ██                                          ██
#    ██                                          ██
#      ██                                      ██  
#        ██                                    ██  
#          ██                              ████    
#            ████                      ████        
#                ██████████████████████            


# Version of this config. Please do not change.
configVersion: 2

# Where do you want phantom to run?
serverInfo:
    host: "localhost"
    port: 25565

# What should the broadcast sent to players look like (number from one to three)?
Style: 1
# Option One:
#                          Upper Message ꖦ
# ████ Lower Message     ⡏ Hover Message ⢹
# ████                   ⣇               ⣸

# Option Two:
#                                    0/0 ꔖ
# ████ Lower Message     ⡏ Hover Message ⢹
# ████                   ⣇               ⣸

# Option Three:
#                                    0/1 ꔖ
# ████ Lower Message     ⡏ Hover Message ⢹
# ████                   ⣇               ⣸


Content:
    # What will the server's MOTD show as? Max 2 lines.
    lowerMessage: |-
      §8[§7§lPhantom§8]
      §f§oThis server is just a broadcast!
    # Text shown above the server (Max ? Chars.)
    upperMessage: §fThis msg appears above the server!
    # This text will appear when someone hovers over the server's status indicator (max 5 ?char lines)
    upperMessage: |-
      §7[§f§lPhantom§7]
      §bThis is some example text
      §3It can be five lines long.
      §3I think at least.
    # What text is sent to users who try to connect to the server?
    kickMessage: |-
      §7[§f§lPhantom§7]
      §4Players who connect will be
      §4kicked with §cthis message§4!
    # Where can we find a 64x64 pixel png image?
    imagePath: server-icon.png